# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9
language: swift
sudo: required
env:
  global:
    - WORKSPACE=Example/IceCream.xcworkspace
    - SCHEME=IceCream-Example
    - SDK=iphonesimulator11.0
  matrix:
    - DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=11.0"
podfile: Example/Podfile
before_script:
  - rm Example/Podfile.lock
  - swift --version
script:
  - set -o pipefail && xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c
