# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9
language: swift
env:
  - BUILD="pod update && set -o pipefail && xcodebuild -workspace IceCream.xcworkspace -scheme IceCream-Example -configuration Release -destination 'platform=iOS Simulator,name=iPhone 8' build | xcpretty"
script:
  - sleep 5
