# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.1

language: swift

sudo: required

env:
  global:
    - WORKSPACE=Example/IceCream.xcworkspace
    - SCHEME=IceCream-Example
    - SDK=iphonesimulator11.1
  matrix:
    - DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=11.1"
podfile: Example/Podfile
script:
  - set -o pipefail && xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c

