# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9
language: swift
env:
  global:
    - WORKSPACE=Example/IceCream.xcworkspace
    - SCHEME=IceCream-Example
    - SDK=iphonesimulator11.0
  matrix:
    - DESTINATION="platform=iOS Simulator,name=iPhone 8,OS=11.0"
script:
  - xcodebuild -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION"
